---

- name: "stat {{ opensearch_config_log4j2_properties }}"
  stat:
    path: "{{ opensearch_config_log4j2_properties }}"
  register: t_opensearch_config_log4j2_properties

- block:
    - name: init log4j2.properties
      copy:
        src: "{{ opensearch_dist_active }}/config/log4j2.properties"
        dest: "{{ opensearch_config_log4j2_properties }}"
        remote_src: yes
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0640"
      register: t_opensearch_log4j2_properties_init

  when: not t_opensearch_config_log4j2_properties.stat.exists


- name: update log4j2.properties
  lineinfile:
    path: "{{ opensearch_config_log4j2_properties }}"
    regexp: "^{{ item.name }}:"
    line: "{{ item.name }}: {{ item.value }}"
    state: "{{ item.state | d('present') }}"
    backrefs: "{{ item.backrefs | d(false) }}"
    insertafter: "{{ item.insertafter | d('^#' + item.name + ':') }}"
  when: item.state is defined or (item.value is not none and item.value is not false)
  loop: "{{ opensearch_conf_log4j2_properties_settings }}"
  register: t_opensearch_log4j2_properties_update



- name: set jvm.options changed
  set_fact:
    t_opensearch_log4j2_properties_changed: ((t_opensearch_config_log4j2_properties_init is defined) and t_opensearch_config_log4j2_properties_init.changed) or t_opensearch_log4j2_properties_update.changed
