---

- include_tasks: workspace.yml
  vars:
    workspace_fs: "{{ opensearch_dir }}"
    workspace_directories: "{{ opensearch_directories }}"

- include_tasks: install_opensearch.yml

- include_tasks: configure_opensearch.yml

- include_tasks: service_opensearch.yml

- include_tasks: configure_post_opensearch.yml
