---

- block:

    # CA
    - name: stat ca key
      stat:
        path: "{{ opensearch_self_signed_ssl_ca_key }}"
      register: t_opensearch_self_signed_ssl_ca_key_stat

    - name: create ca key
      command: 'openssl genrsa -out "{{ opensearch_self_signed_ssl_ca_key }}" {{ opensearch_self_signed_ssl_ca_key_size }}'
      register: t_opensearch_self_signed_ssl_ca_key_update
      when: not t_opensearch_self_signed_ssl_ca_key_stat.stat.exists

    - name: ca key permission
      file:
        path: "{{ opensearch_self_signed_ssl_ca_key }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0600"

    - name: stat ca cert
      stat:
        path: "{{ opensearch_self_signed_ssl_ca_cert }}"
      register: t_opensearch_self_signed_ssl_ca_cert_stat

    - name: create ca cert
      command: 'openssl req -new -x509 -sha256 -key "{{ opensearch_self_signed_ssl_ca_key }}" -subj "{{ opensearch_self_signed_ssl_ca_dn }}" -out "{{ opensearch_self_signed_ssl_ca_cert }}" -days {{ opensearch_self_signed_ssl_ca_cert_days }}'
      register: t_opensearch_self_signed_ssl_ca_cert_update
      when: not t_opensearch_self_signed_ssl_ca_cert_stat.stat.exists or t_opensearch_self_signed_ssl_ca_key_update.changed

    - name: ca cert permission
      file:
        path: "{{ opensearch_self_signed_ssl_ca_cert }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0644"


    # admin
    - name: stat admin key
      stat:
        path: "{{ opensearch_self_signed_ssl_admin_key }}"
      register: t_opensearch_self_signed_ssl_admin_key_stat

    - block:
        - name: create admin key
          command: 'openssl genrsa -out "{{ opensearch_self_signed_ssl_admin_key }}.tmp" {{ opensearch_self_signed_ssl_admin_key_size }}'

        - name: format admin key to pkcs8
          command: 'openssl pkcs8 -inform PEM -outform PEM -in "{{ opensearch_self_signed_ssl_admin_key }}.tmp" -topk8 -nocrypt -v1 PBE-SHA1-3DES -out "{{ opensearch_self_signed_ssl_admin_key }}"'
          register: t_opensearch_self_signed_ssl_admin_key_update

        - name: clean tmp admin key
          file:
            path: "{{ opensearch_self_signed_ssl_admin_key }}.tmp"
            state: absent

      when: not t_opensearch_self_signed_ssl_admin_key_stat.stat.exists

    - name: admin key permission
      file:
        path: "{{ opensearch_self_signed_ssl_admin_key }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0600"

    - name: stat admin cert
      stat:
        path: "{{ opensearch_self_signed_ssl_admin_cert }}"
      register: t_opensearch_self_signed_ssl_admin_cert_stat

    - block:
        - name: create admin req
          command: 'openssl req -new -key "{{ opensearch_self_signed_ssl_admin_key }}" -subj "{{ opensearch_self_signed_ssl_admin_dn }}" -out "{{ opensearch_self_signed_ssl_admin_cert }}.csr"'

        - name: sign admin cert
          command: 'openssl x509 -req -in "{{ opensearch_self_signed_ssl_admin_cert }}.csr" -CA "{{ opensearch_self_signed_ssl_ca_cert }}" -CAkey "{{ opensearch_self_signed_ssl_ca_key }}" -CAcreateserial -sha256 -out "{{ opensearch_self_signed_ssl_admin_cert }}" -days {{ opensearch_self_signed_ssl_admin_cert_days }}'

          register: t_opensearch_self_signed_ssl_admin_cert_update

        - name: clean admin req
          file:
            path: "{{ opensearch_self_signed_ssl_admin_cert }}.csr"
            state: absent

      when: not t_opensearch_self_signed_ssl_admin_cert_stat.stat.exists or t_opensearch_self_signed_ssl_admin_key_update.changed

    - name: admin cert permission
      file:
        path: "{{ opensearch_self_signed_ssl_admin_cert }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0644"


    # node
    - name: stat node key
      stat:
        path: "{{ opensearch_self_signed_ssl_node_key }}"
      register: t_opensearch_self_signed_ssl_node_key_stat

    - block:
        - name: create node key
          command: 'openssl genrsa -out "{{ opensearch_self_signed_ssl_node_key }}.tmp" {{ opensearch_self_signed_ssl_node_key_size }}'

        - name: format node key to pkcs8
          command: 'openssl pkcs8 -inform PEM -outform PEM -in "{{ opensearch_self_signed_ssl_node_key }}.tmp" -topk8 -nocrypt -v1 PBE-SHA1-3DES -out "{{ opensearch_self_signed_ssl_node_key }}"'
          register: t_opensearch_self_signed_ssl_node_key_update

        - name: clean tmp node key
          file:
            path: "{{ opensearch_self_signed_ssl_node_key }}.tmp"
            state: absent

      when: not t_opensearch_self_signed_ssl_node_key_stat.stat.exists

    - name: node key permission
      file:
        path: "{{ opensearch_self_signed_ssl_node_key }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0600"

    - name: stat node cert
      stat:
        path: "{{ opensearch_self_signed_ssl_node_cert }}"
      register: t_opensearch_self_signed_ssl_node_cert_stat

    - block:
        - name: create node req
          command: 'openssl req -new -key "{{ opensearch_self_signed_ssl_node_key }}" -subj "{{ opensearch_self_signed_ssl_node_dn }}" -out "{{ opensearch_self_signed_ssl_node_cert }}.csr"'

        - name: create node req ext
          copy:
            dest: "{{ opensearch_self_signed_ssl_node_cert }}.csr.ext"
            content: "subjectAltName=DNS:{{ opensearch_node_fqdn }},DNS:{{ opensearch_service_dns }},DNS:{{ opensearch_dashboards_service_dns }}"
            owner: "{{ opensearch_admin_user }}"
            group: "{{ opensearch_group }}"
            mode: "0644"

        - name: sign node cert
          command: 'openssl x509 -req -in "{{ opensearch_self_signed_ssl_node_cert }}.csr" -CA "{{ opensearch_self_signed_ssl_ca_cert }}" -CAkey "{{ opensearch_self_signed_ssl_ca_key }}" -CAcreateserial -sha256 -out "{{ opensearch_self_signed_ssl_node_cert }}" -days {{ opensearch_self_signed_ssl_node_cert_days }} -extfile "{{ opensearch_self_signed_ssl_node_cert }}.csr.ext"'

          register: t_opensearch_self_signed_ssl_node_cert_update

        - name: clean node req
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ opensearch_self_signed_ssl_node_cert }}.csr"
            - "{{ opensearch_self_signed_ssl_node_cert }}.csr.ext"

      when: not t_opensearch_self_signed_ssl_node_cert_stat.stat.exists or t_opensearch_self_signed_ssl_node_key_update.changed

    - name: node cert permission
      file:
        path: "{{ opensearch_self_signed_ssl_node_cert }}"
        owner: "{{ opensearch_admin_user }}"
        group: "{{ opensearch_group }}"
        mode: "0644"


  when: opensearch_use_self_signed_ssl



# - name: stat ca cert
#   stat:
#     path: "{{ opensearch_self_signed_ssl_ca_cert }}"
#   register: t_opensearch_self_signed_ssl_ca_cert_stat

# - name: stat admin cert
#   stat:
#     path: "{{ opensearch_self_signed_ssl_admin_cert }}"
#   register: t_opensearch_self_signed_ssl_admin_cert

# - name: stat admin key
#   stat:
#     path: "{{ opensearch_self_signed_ssl_admin_key }}"
#   register: t_opensearch_self_signed_ssl_admin_key

# - name: stat node cert
#   stat:
#     path: "{{ opensearch_self_signed_ssl_node_cert }}"
#   register: t_opensearch_self_signed_ssl_node_cert

# - name: stat node key
#   stat:
#     path: "{{ opensearch_self_signed_ssl_node_key }}"
#   register: t_opensearch_self_signed_ssl_node_key


# - name: ensure certs are present
#   fail:
#     msg: "missing certificates"
#   when: not t_opensearch_self_signed_ssl_ca_cert_stat.stat.exists or not t_opensearch_self_signed_ssl_admin_cert.stat.exists or not t_opensearch_self_signed_ssl_admin_key.stat.exists or not t_opensearch_self_signed_ssl_node_cert.stat.exists or not t_opensearch_self_signed_ssl_node_key.stat.exists
